### ISSUE TITLE
Unknown result backend: 'redis://'

### ISSUE THREAD

**Issue by globalqss** [notifico/notifico#125]
After solving #124 I found another error when running:

```
# python -m notifico init
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/notifico/notifico/__main__.py", line 49, in <module>
    sys.exit(main(sys.argv))
  File "/tmp/notifico/notifico/__main__.py", line 38, in main
    app = create_instance()
  File "notifico/__init__.py", line 104, in create_instance
    from notifico.views.account import account
  File "notifico/views/account/__init__.py", line 19, in <module>
    from notifico.services import reset, background
  File "notifico/services/background.py", line 7, in <module>
    @celery.task
  File "/usr/lib/python2.7/dist-packages/celery/app/__init__.py", line 191, in task
    return inner_create_task_cls(**options)(*args)
  File "/usr/lib/python2.7/dist-packages/celery/app/__init__.py", line 171, in _create_task_cls
    base = options.pop("base", None) or self.Task
  File "/usr/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 262, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/lib/python2.7/dist-packages/celery/app/__init__.py", line 197, in Task
    return self.create_task_cls()
  File "/usr/lib/python2.7/dist-packages/celery/app/__init__.py", line 95, in create_task_cls
    class Task(BaseTask):
  File "/usr/lib/python2.7/dist-packages/celery/app/__init__.py", line 98, in Task
    backend = self.backend
  File "/usr/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 262, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/lib/python2.7/dist-packages/celery/app/base.py", line 386, in backend
    return self._get_backend()
  File "/usr/lib/python2.7/dist-packages/celery/app/base.py", line 341, in _get_backend
    backend_cls = get_backend_cls(backend_cls, loader=self.loader)
  File "/usr/lib/python2.7/dist-packages/celery/utils/functional.py", line 48, in _M
    value = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/backends/__init__.py", line 31, in get_backend_cls
    "Did you spell it correctly?  (%s)" % (backend, exc))
ValueError: Unknown result backend: 'redis://'.  Did you spell it correctly?  (Couldn't import 'redis://': Empty module name)
```

The next patch solved the problem:
```
diff --git a/notifico/services/background.py b/notifico/services/background.py
index 85c72b2..0261fef 100644
--- a/notifico/services/background.py
+++ b/notifico/services/background.py
@@ -4,7 +4,7 @@ from flask.ext.mail import Message
 from notifico import create_instance, celery, mail
 
 
-@celery.task
+celery.task
 def send_mail(*args, **kwargs):
     """
     Sends an email using Flask-Mail and Notifico's configuration
```

Now, notifico is working fine in our server - thanks a lot @TkTech for this.

Regards,

Carlos Ruiz
http://wiki.idempiere.org/en/User:CarlosRuiz

**Comment by Dav1dde** [comment]
This is *not* a solution, `@clery.task` is a decorator, your patch is equal to removing the decorator from this function.

Try changing `CELERY_RESULT_BACKEND` in `config.py` to `redis`:

```python
BROKER_URL = 'redis://'
CELERY_RESULT_BACKEND = 'redis'
CELERY_IMPORTS = ('notifico.services.background',)
CELERY_TASK_SERIALIZER = 'json'
```

I am not sure why you get this problem, since I am not familiar with celery. @TkTech  ?

**Comment by globalqss** [comment]
Thanks @Dav1dde you're right, then the correct patch seems to be:
```
diff --git a/notifico/config.py b/notifico/config.py
index c353567..16412dc 100644
--- a/notifico/config.py
+++ b/notifico/config.py
@@ -65,7 +65,7 @@ SENTRY_DSN = None
 # Celery Configuration
 # ---
 BROKER_URL = 'redis://'
-CELERY_RESULT_BACKEND = 'redis://'
+CELERY_RESULT_BACKEND = 'redis'
 CELERY_IMPORTS = ('notifico.services.background',)
 CELERY_TASK_SERIALIZER = 'json'
 
```

**Comment by Dav1dde** [comment]
I am not sure why it broke out of the sudden and if this is the correct fix, according to the [documentation](http://celery.readthedocs.org/en/latest/internals/reference/celery.backends.html#celery.backends.get_backend_by_url) celery has two methods of creating the backend, `get_backend_cls` is used instead of `get_backend_by_url` (which worked before). 

For now you do not need to patch notifico, simply override the value in your `local_config.py`.

**Comment by TkTech** [comment]
This isn't really a bug - different versions and combinations of redis and celery accept different default strings for the CELERY_RESULT_BACKEND. We can always make the default more explicit which should always work.
